/**
 * The defined color constants as a typescript enum
 */
declare enum AllColors {
    /**
     * COMPLETE COLOR PALETTE
     * -------------------------------------------------------------------
     * Variable names generated by Name That Color
     * http://chir.ag/projects/name-that-color
     */
    Monza,
    Tangerine,
    Corn,
    Sun,
    Porsche,
    Korma,
    Punch,
    AlizarinCrimson,
    Mandy,
    RedRibbon,
    DeepBlush,
    Cerise,
    RoseBudCherry,
    EastSide,
    Seance,
    ShipCove,
    StTropaz,
    CongressBlue,
    Cerulean,
    Endeavour,
    LightCerulean,
    DeepCerulean,
    MonteCarlo,
    BlueLagoon,
    PersianGreen,
    TropicalRainForrest,
    Mantis,
    Apple,
    Celery,
    Limeade,
    Asparagus,
    GreenLeaf,
    Kabul,
    Nepal,
    BlackPearl,
    /**
     * GRAYSCALE COLOR PALETTE
     * -------------------------------------------------------------------
     * Collection of grayscale colors
     */
    Black,
    GreyDark,
    Grey,
    GreyLight,
    GreyLighter,
    White,
    /**
     * SOCIAL BRAND COLOR PALETTE
     * -------------------------------------------------------------------
     * Collection of social branding colors
     */
    Twitter,
    Linkedin,
    Facebook,
    Google,
    Snapchat,
    InstagramYellowLight,
    InstagramYellowDark,
    InstagramOrange,
    InstagramRed,
    InstagramBlue,
    InstagramPurple,
}
export default AllColors;
