"use strict";
exports.__esModule = true;
/**
 * The defined color constants as a typescript enum
 */
var AllColors;
(function (AllColors) {
    /**
     * COMPLETE COLOR PALETTE
     * -------------------------------------------------------------------
     * Variable names generated by Name That Color
     * http://chir.ag/projects/name-that-color
     */
    AllColors[AllColors["Monza"] = "rgb(207, 0, 57)"] = "Monza";
    AllColors[AllColors["Tangerine"] = "rgb(241, 138, 0)"] = "Tangerine";
    AllColors[AllColors["Corn"] = "rgb(220, 198, 0)"] = "Corn";
    AllColors[AllColors["Sun"] = "rgb(249, 176, 30)"] = "Sun";
    AllColors[AllColors["Porsche"] = "rgb(236, 161, 84)"] = "Porsche";
    AllColors[AllColors["Korma"] = "rgb(148, 69, 11)"] = "Korma";
    AllColors[AllColors["Punch"] = "rgb(224, 78, 57)"] = "Punch";
    AllColors[AllColors["AlizarinCrimson"] = "rgb(218, 41, 28)"] = "AlizarinCrimson";
    AllColors[AllColors["Mandy"] = "rgb(223, 70, 97)"] = "Mandy";
    AllColors[AllColors["RedRibbon"] = "rgb(228, 0, 70)"] = "RedRibbon";
    AllColors[AllColors["DeepBlush"] = "rgb(229, 109, 177)"] = "DeepBlush";
    AllColors[AllColors["Cerise"] = "rgb(227, 49, 138)"] = "Cerise";
    AllColors[AllColors["RoseBudCherry"] = "rgb(132, 11, 85)"] = "RoseBudCherry";
    AllColors[AllColors["EastSide"] = "rgb(181, 128, 209)"] = "EastSide";
    AllColors[AllColors["Seance"] = "rgb(105, 31, 130)"] = "Seance";
    AllColors[AllColors["ShipCove"] = "rgb(103, 135, 183)"] = "ShipCove";
    AllColors[AllColors["StTropaz"] = "rgb(44, 86, 151)"] = "StTropaz";
    AllColors[AllColors["CongressBlue"] = "rgb(0, 64, 136)"] = "CongressBlue";
    AllColors[AllColors["Cerulean"] = "rgb(0, 145, 211)"] = "Cerulean";
    AllColors[AllColors["Endeavour"] = "rgb(0, 100, 180)"] = "Endeavour";
    AllColors[AllColors["LightCerulean"] = "rgb(0, 160, 211)"] = "LightCerulean";
    AllColors[AllColors["DeepCerulean"] = "rgb(0, 127, 163)"] = "DeepCerulean";
    AllColors[AllColors["MonteCarlo"] = "rgb(127, 202, 211)"] = "MonteCarlo";
    AllColors[AllColors["BlueLagoon"] = "rgb(0, 140, 149)"] = "BlueLagoon";
    AllColors[AllColors["PersianGreen"] = "rgb(0, 152, 130)"] = "PersianGreen";
    AllColors[AllColors["TropicalRainForrest"] = "rgb(0, 123, 95)"] = "TropicalRainForrest";
    AllColors[AllColors["Mantis"] = "rgb(108, 194, 74)"] = "Mantis";
    AllColors[AllColors["Apple"] = "rgb(74, 163, 44)"] = "Apple";
    AllColors[AllColors["Celery"] = "rgb(170, 203, 87)"] = "Celery";
    AllColors[AllColors["Limeade"] = "rgb(122, 154, 1)"] = "Limeade";
    AllColors[AllColors["Asparagus"] = "rgb(120, 157, 74)"] = "Asparagus";
    AllColors[AllColors["GreenLeaf"] = "rgb(87, 115, 7)"] = "GreenLeaf";
    AllColors[AllColors["Kabul"] = "rgb(85, 71, 65)"] = "Kabul";
    AllColors[AllColors["Nepal"] = "rgb(144, 171, 188)"] = "Nepal";
    AllColors[AllColors["BlackPearl"] = "rgb(8, 31, 44)"] = "BlackPearl";
    /**
     * GRAYSCALE COLOR PALETTE
     * -------------------------------------------------------------------
     * Collection of grayscale colors
     */
    AllColors[AllColors["Black"] = "rgb(0, 0, 0)"] = "Black";
    AllColors[AllColors["GreyDark"] = "rgb(125, 125, 125)"] = "GreyDark";
    AllColors[AllColors["Grey"] = "rgb(176, 176, 176)"] = "Grey";
    AllColors[AllColors["GreyLight"] = "rgb(216, 216, 216)"] = "GreyLight";
    AllColors[AllColors["GreyLighter"] = "rgb(243, 243, 243)"] = "GreyLighter";
    AllColors[AllColors["White"] = "rgb(255, 255, 255)"] = "White";
    /**
     * SOCIAL BRAND COLOR PALETTE
     * -------------------------------------------------------------------
     * Collection of social branding colors
     */
    AllColors[AllColors["Twitter"] = "rgb(0, 172, 237)"] = "Twitter";
    AllColors[AllColors["Linkedin"] = "rgb(0, 119, 181)"] = "Linkedin";
    AllColors[AllColors["Facebook"] = "rgb(59, 89, 152)"] = "Facebook";
    AllColors[AllColors["Google"] = "rgb(220, 78, 65)"] = "Google";
    AllColors[AllColors["Snapchat"] = "rgb(255, 252, 0)"] = "Snapchat";
    AllColors[AllColors["InstagramYellowLight"] = "rgb(255, 225, 125)"] = "InstagramYellowLight";
    AllColors[AllColors["InstagramYellowDark"] = "rgb(255, 205, 105)"] = "InstagramYellowDark";
    AllColors[AllColors["InstagramOrange"] = "rgb(250, 145, 55)"] = "InstagramOrange";
    AllColors[AllColors["InstagramRed"] = "rgb(235, 65, 65)"] = "InstagramRed";
    AllColors[AllColors["InstagramBlue"] = "rgb(35, 75, 215)"] = "InstagramBlue";
    AllColors[AllColors["InstagramPurple"] = "rgb(195, 60, 190)"] = "InstagramPurple";
})(AllColors || (AllColors = {}));
exports["default"] = AllColors;
